name: pyviz-topics
channels:
  - pyviz
dependencies:
  - python=3.6
  - notebook ==5.7.8
  - ipykernel ==5.1.0
  - bokeh ==1.1.0
  - cartopy ==0.17.0
  - colorcet ==2.0.1
  - dask ==1.2.2
  - datashader ==0.7.0
  - fastparquet ==0.3.0
  - geoviews ==1.6.2
  - holoviews ==1.12.3
  - matplotlib ==3.0.3
  - networkx ==2.3
  - numba ==0.43.1
  - numpy ==1.16.3
  - pandas ==0.24.2
  - python-snappy ==0.5.4
  - rasterio ==1.0.21
  - xarray ==0.12.1
