name: examples-gallery-manage
channels:
  - conda-forge
  - pyviz
  - ae5-admin
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - doit
  - python-dotenv
  - pyyaml
  - anaconda-project
  - intake
  - nbclient
  - nbformat
  - ae5-tools
  - nbqa
  - flake8
  - sphinx
  - myst-nb
  - sphinx-design
  - sphinx-copybutton
  - sphinxext-rediraffe
  - nbsite=0.8.2
  - nbval >= 0.10.0
